import { useCallback, useEffect, useMemo, useState } from 'react'

export const GAME_DEFINITIONS = [
  { id: 'tic', route: 'tic-tac-toe', onlineKey: 'tic_tac_toe', title: 'Tic-tac-toe', eyebrow: 'Quick strategy', description: 'Read the board, block the Owl, and land the cleverest three-in-a-row.', tone: 'blue', icon: '×○', accent: '#5B8DEF', guide: ['Take turns placing your mark.', 'You are X. The Owl is O.', 'Make three in a row across, down, or diagonally.'] },
  { id: 'memory', route: 'memory-cards', onlineKey: 'memory_cards', title: 'Memory cards', eyebrow: 'Focus sprint', description: 'Build a streak by finding pairs before your attention wanders.', tone: 'gold', icon: '◐◑', accent: '#E6B84B', guide: ['Flip two cards at a time.', 'If the symbols match, you keep the pair.', 'Find every pair with as few turns as possible.'] },
  { id: 'snake', route: 'owl-snake', onlineKey: null, title: 'Owl Snake', eyebrow: 'Score chase', description: 'Collect moon-stars, grow your trail, and beat your personal best.', tone: 'green', icon: '●', accent: '#56B69A', guide: ['Use the arrows or the touch pad to fly.', 'Collect stars to grow your trail and score.', 'Avoid the edges and your own tail.'] },
  { id: 'connect', route: 'connect-four', onlineKey: 'connect_four', title: 'Connect Four', eyebrow: 'Tactical duel', description: 'Control the middle, set a trap, and connect four glowing tokens.', tone: 'purple', icon: '✦', accent: '#A985F3', guide: ['Drop one token into a column each turn.', 'Tokens fall to the lowest open space.', 'Connect four in a row before your rival.'] },
  { id: 'ludo', route: 'ludo', onlineKey: 'ludo', title: 'Owl Ludo', eyebrow: 'Race & roll', description: 'Roll lucky numbers, move your pieces, and race the Owl home.', tone: 'coral', icon: '◆', accent: '#E17863', guide: ['Roll the die when it is your turn.', 'Move one piece by the number you roll.', 'Reach the nest first to win the round.'] },
  { id: 'chess', route: 'chess', onlineKey: null, title: 'Owl Chess', eyebrow: 'Quiet strategy', description: 'Build a plan, protect your pieces, and outthink the Owl one move at a time.', tone: 'gold', icon: '♞', accent: '#C99B52', guide: ['Tap one of your white pieces to see its legal moves.', 'Tap a highlighted square to move or capture.', 'Reach the Owl king to win this practice round.'] },
]

export const DIFFICULTIES = {
  easy: { id: 'easy', label: 'Easy', description: 'Gentle practice with more help.', color: '#56B69A' },
  standard: { id: 'standard', label: 'Standard', description: 'The balanced everyday challenge.', color: '#5B8DEF' },
  hard: { id: 'hard', label: 'Hard', description: 'Less help, faster decisions, sharper play.', color: '#D8795B' },
}

const REACTIONS = { welcome: 'The Owl is ready when you are.', win: 'Brilliant move. That was worth a tiny victory flap.', draw: 'A draw! The Owl respects a worthy rival.', match: 'Nice match. Your focus is getting stronger.', score: 'New high-score energy. Keep going!' }

export function getGameDefinition(id) { return GAME_DEFINITIONS.find((game) => game.id === id) || GAME_DEFINITIONS[0] }
export function usePlaygroundReaction() { const [reaction, setReaction] = useState(REACTIONS.welcome); return { reaction, react: (key) => setReaction(REACTIONS[key] || REACTIONS.welcome) } }
export function getSavedDifficulty(gameId) { return window.localStorage.getItem(`dk_playground_difficulty_${gameId}`) || 'standard' }
export function saveDifficulty(gameId, difficulty) { window.localStorage.setItem(`dk_playground_difficulty_${gameId}`, difficulty) }

export function DifficultySelector({ gameId, value, onChange }) {
  return <div className="dk-difficulty-control" aria-label="Game difficulty"><div><span className="dk-kicker">Challenge level</span><strong>{DIFFICULTIES[value].label}</strong><small>{DIFFICULTIES[value].description}</small></div><div className="dk-difficulty-options">{Object.values(DIFFICULTIES).map((item) => <button type="button" key={item.id} className={value === item.id ? 'is-active' : ''} onClick={() => { saveDifficulty(gameId, item.id); onChange(item.id) }} style={{ '--difficulty-color': item.color }}>{item.label}</button>)}</div></div>
}

function resetTic() { return { board: Array(9).fill(null), turn: 'X', winner: null } }
function checkTicWinner(board) { const lines = [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]]; for (const [a,b,c] of lines) if (board[a] && board[a] === board[b] && board[a] === board[c]) return board[a]; return board.every(Boolean) ? 'draw' : null }
function chooseOwlMove(board, difficulty) { const empty = board.map((value, index) => value ? null : index).filter((value) => value !== null); if (!empty.length) return undefined; if (difficulty === 'easy') return empty[Math.floor(Math.random() * empty.length)]; const winning = (mark) => empty.find((index) => { const next = [...board]; next[index] = mark; return checkTicWinner(next) === mark }); return winning('O') ?? (difficulty === 'hard' ? winning('X') : undefined) ?? (board[4] ? empty[Math.floor(Math.random() * empty.length)] : 4) }

export function TicTacToeGame({ onReact, difficulty = 'standard' }) {
  const [game, setGame] = useState(resetTic); const [mode, setMode] = useState('owl')
  const makeMove = useCallback((index, player = game.turn) => { if (game.board[index] || game.winner || (mode === 'owl' && player === 'O')) return; const board = [...game.board]; board[index] = player; const winner = checkTicWinner(board); setGame({ board, turn: player === 'X' ? 'O' : 'X', winner }); if (winner) onReact(winner === 'draw' ? 'draw' : 'win') }, [game, mode, onReact])
  useEffect(() => { if (mode !== 'owl' || game.turn !== 'O' || game.winner) return undefined; const timeout = window.setTimeout(() => { const choice = chooseOwlMove(game.board, difficulty); if (choice !== undefined) { const board = [...game.board]; board[choice] = 'O'; const winner = checkTicWinner(board); setGame({ board, turn: 'X', winner }); if (winner) onReact(winner === 'draw' ? 'draw' : 'win') } }, difficulty === 'hard' ? 300 : 560); return () => window.clearTimeout(timeout) }, [game, mode, difficulty, onReact])
  const reset = (nextMode = mode) => { setMode(nextMode); setGame(resetTic()) }; const status = game.winner ? (game.winner === 'draw' ? 'Draw game' : `${game.winner === 'X' ? 'You' : 'Owl'} win`) : `${game.turn === 'X' ? 'Your' : mode === 'owl' ? 'Owl' : 'Player 2'} turn`
  return <div className="dk-game-panel dk-modern-game-panel"><div className="dk-game-toolbar"><span className="dk-live-status"><i />{status}</span><div className="dk-mode-switch"><button type="button" className={mode === 'owl' ? 'is-active' : ''} onClick={() => reset('owl')}>Vs Owl</button><button type="button" className={mode === 'local' ? 'is-active' : ''} onClick={() => reset('local')}>Two players</button></div></div><div className="dk-tic-grid dk-tic-grid-modern">{game.board.map((value, index) => <button type="button" key={index} className={`dk-tic-cell ${value ? 'is-filled' : ''}`} onClick={() => makeMove(index)} aria-label={`Cell ${index + 1}${value ? `, ${value}` : ''}`}>{value === 'X' ? '×' : value === 'O' ? '○' : <span>+</span>}</button>)}</div><div className="dk-game-footer"><p aria-live="polite">{game.winner ? 'Ready for a rematch?' : `${DIFFICULTIES[difficulty].label} Owl challenge. Three in a row wins.`}</p><button type="button" className="dk-secondary-button" onClick={() => reset()}>Restart</button></div></div>
}

function makeDeck(difficulty) { const pairs = difficulty === 'easy' ? ['owl','owl','star','star','moon','moon'] : difficulty === 'hard' ? ['owl','owl','star','star','moon','moon','bolt','bolt','sun','sun','gem','gem'] : ['owl','owl','star','star','moon','moon','bolt','bolt']; return pairs.sort(() => Math.random() - 0.5).map((value, index) => ({ id: index, value, revealed: false, matched: false })) }
export function MemoryGame({ onReact, difficulty = 'standard' }) {
  const [cards, setCards] = useState(() => makeDeck(difficulty)); const [flipped, setFlipped] = useState([]); const [turn, setTurn] = useState(1); const [scores, setScores] = useState({ 1: 0, 2: 0 })
  useEffect(() => { if (flipped.length !== 2) return undefined; const [first, second] = flipped.map((id) => cards.find((card) => card.id === id)); const timeout = window.setTimeout(() => { if (first.value === second.value) { setCards((current) => current.map((card) => card.id === first.id || card.id === second.id ? { ...card, matched: true } : card)); setScores((current) => ({ ...current, [turn]: current[turn] + 1 })); onReact('match') } else setTurn((current) => current === 1 ? 2 : 1); setFlipped([]) }, difficulty === 'hard' ? 420 : 650); return () => window.clearTimeout(timeout) }, [flipped, cards, onReact, turn, difficulty])
  const flip = (id) => { if (flipped.length === 2 || flipped.includes(id)) return; const card = cards.find((item) => item.id === id); if (!card || card.matched || card.revealed) return; setCards((current) => current.map((item) => item.id === id ? { ...item, revealed: true } : item)); setFlipped((current) => [...current, id]) }; const restart = () => { setCards(makeDeck(difficulty)); setFlipped([]); setScores({ 1: 0, 2: 0 }); setTurn(1) }; const complete = cards.every((card) => card.matched)
  return <div className="dk-game-panel dk-modern-game-panel"><div className="dk-game-toolbar"><span className="dk-live-status"><i />Player {turn}'s turn</span><span className="dk-score-chip">{scores[1]} : {scores[2]}</span></div><div className={`dk-memory-grid dk-memory-grid-modern dk-memory-${difficulty}`} aria-label="Memory cards">{cards.map((card) => <button type="button" key={card.id} className={`dk-memory-card ${card.revealed || card.matched ? 'is-open' : ''} ${card.matched ? 'is-matched' : ''}`} onClick={() => flip(card.id)} aria-label={card.revealed || card.matched ? `${card.value} card` : 'Hidden memory card'}><span>{card.revealed || card.matched ? ({ owl: '🦉', star: '★', moon: '☾', bolt: '✦', sun: '☀', gem: '◆' }[card.value]) : '?'}</span></button>)}</div><div className="dk-game-footer"><p aria-live="polite">{complete ? 'All pairs found. Lovely focus!' : `${DIFFICULTIES[difficulty].label}: find ${cards.length / 2} pairs.`}</p><button type="button" className="dk-secondary-button" onClick={restart}>Restart</button></div></div>
}

export function ConnectFourGame({ onReact, difficulty = 'standard' }) {
  const columns = 7; const rows = 6; const [board, setBoard] = useState(() => Array(rows * columns).fill(null)); const [turn, setTurn] = useState('X'); const [winner, setWinner] = useState(null)
  const drop = (column) => { if (winner) return; let row = rows - 1; while (row >= 0 && board[row * columns + column]) row -= 1; if (row < 0) return; const next = [...board]; next[row * columns + column] = turn; const directions = [[1,0],[0,1],[1,1],[1,-1]]; const count = (dx,dy) => { let total = 1; for (const sign of [-1,1]) { let x = column + dx * sign; let y = row + dy * sign; while (x >= 0 && x < columns && y >= 0 && y < rows && next[y * columns + x] === turn) { total += 1; x += dx * sign; y += dy * sign } } return total }; const won = directions.some(([dx,dy]) => count(dx,dy) >= 4); setBoard(next); setWinner(won ? turn : next.every(Boolean) ? 'draw' : null); setTurn(turn === 'X' ? 'O' : 'X'); if (won) onReact('win'); else if (next.every(Boolean)) onReact('draw') }
  const reset = () => { setBoard(Array(rows * columns).fill(null)); setTurn('X'); setWinner(null) }
  return <div className="dk-game-panel dk-modern-game-panel"><div className="dk-game-toolbar"><span className="dk-live-status"><i />{winner ? winner === 'draw' ? 'Draw game' : `${winner === 'X' ? 'Player 1' : 'Player 2'} wins` : `${turn === 'X' ? 'Player 1' : 'Player 2'} turn`}</span><span className="dk-score-chip">{DIFFICULTIES[difficulty].label} duel</span></div><div className="dk-connect-board dk-connect-board-modern" role="grid" aria-label="Connect Four board">{Array.from({ length: columns }, (_, column) => <button key={column} type="button" className="dk-connect-column" onClick={() => drop(column)} aria-label={`Drop token in column ${column + 1}`}>{Array.from({ length: rows }, (_, row) => <span key={row} className={`dk-connect-slot ${board[row * columns + column] === 'X' ? 'is-red' : board[row * columns + column] === 'O' ? 'is-gold' : ''}`} />)}</button>)}</div><div className="dk-game-footer"><p aria-live="polite">{winner ? 'Ready for another strategy round?' : `${DIFFICULTIES[difficulty].label}: control the middle and connect four.`}</p><button type="button" className="dk-secondary-button" onClick={reset}>Restart</button></div></div>
}

export function SnakeGame({ onReact, difficulty = 'standard' }) {
  const size = 14; const speed = difficulty === 'easy' ? 240 : difficulty === 'hard' ? 125 : 180; const [snake, setSnake] = useState([{ x: 6, y: 7 }, { x: 5, y: 7 }, { x: 4, y: 7 }]); const [food, setFood] = useState({ x: 10, y: 5 }); const [direction, setDirection] = useState({ x: 1, y: 0 }); const [running, setRunning] = useState(false); const [score, setScore] = useState(0); const [best, setBest] = useState(() => Number(window.localStorage.getItem('dk_owl_snake_best') || 0))
  const reset = () => { setSnake([{ x: 6, y: 7 }, { x: 5, y: 7 }, { x: 4, y: 7 }]); setFood({ x: 10, y: 5 }); setDirection({ x: 1, y: 0 }); setScore(0); setRunning(false) }; useEffect(() => { const onKey = (event) => { const keys = { ArrowUp: { x: 0, y: -1 }, ArrowDown: { x: 0, y: 1 }, ArrowLeft: { x: -1, y: 0 }, ArrowRight: { x: 1, y: 0 } }; if (keys[event.key]) { event.preventDefault(); const next = keys[event.key]; if (next.x + direction.x !== 0 || next.y + direction.y !== 0) setDirection(next); setRunning(true) } }; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey) }, [direction])
  useEffect(() => { if (!running) return undefined; const timer = window.setInterval(() => setSnake((current) => { const head = { x: current[0].x + direction.x, y: current[0].y + direction.y }; const hit = head.x < 0 || head.y < 0 || head.x >= size || head.y >= size || current.some((part) => part.x === head.x && part.y === head.y); if (hit) { setRunning(false); onReact('score'); return current } const next = [head, ...current]; if (head.x === food.x && head.y === food.y) { setScore((value) => { const nextScore = value + 1; setBest((bestScore) => { const nextBest = Math.max(bestScore, nextScore); window.localStorage.setItem('dk_owl_snake_best', String(nextBest)); return nextBest }); return nextScore }); setFood({ x: Math.floor(Math.random() * size), y: Math.floor(Math.random() * size) }) } else next.pop(); return next }), speed); return () => window.clearInterval(timer) }, [running, direction, food, onReact, speed])
  const cells = useMemo(() => Array.from({ length: size * size }, (_, index) => ({ x: index % size, y: Math.floor(index / size) })), []); const steer = (next) => { if (next.x + direction.x !== 0 || next.y + direction.y !== 0) setDirection(next); setRunning(true) }
  return <div className="dk-game-panel dk-modern-game-panel"><div className="dk-game-toolbar"><span className="dk-live-status"><i />{running ? 'Flight in progress' : score ? 'Round over' : 'Ready to fly'}</span><span className="dk-score-chip">Score {score} · Best {best}</span></div><div className="dk-snake-board dk-snake-board-modern" role="img" aria-label={`Owl Snake board. Score ${score}. Use arrow keys or controls below.`}>{cells.map((cell) => { const part = snake.find((item) => item.x === cell.x && item.y === cell.y); const isFood = food.x === cell.x && food.y === cell.y; return <span key={`${cell.x}-${cell.y}`} className={`dk-snake-cell ${part ? 'is-snake' : ''} ${isFood ? 'is-food' : ''}`}>{part && cell.x === snake[0].x && cell.y === snake[0].y ? '🦉' : isFood ? '★' : ''}</span> })}</div><div className="dk-snake-controls"><button type="button" onClick={() => steer({ x: 0, y: -1 })}>↑</button><div><button type="button" onClick={() => steer({ x: -1, y: 0 })}>←</button><button type="button" onClick={() => steer({ x: 0, y: 1 })}>↓</button><button type="button" onClick={() => steer({ x: 1, y: 0 })}>→</button></div></div><div className="dk-game-footer"><p>{running ? `${DIFFICULTIES[difficulty].label}: collect moon-stars and avoid the edges.` : score ? 'Your score is safe. Ready for another flight?' : 'Press a direction to launch.'}</p><button type="button" className="dk-secondary-button" onClick={reset}>Restart</button></div></div>
}

export function LudoGame({ onReact, difficulty = 'standard' }) {
  const finish = 28
  const [positions, setPositions] = useState({ you: 0, owl: 0 }); const [turn, setTurn] = useState('you'); const [die, setDie] = useState(null); const [winner, setWinner] = useState(null)
  const roll = useCallback(() => { if (winner || turn !== 'you') return; const value = Math.floor(Math.random() * 6) + 1; const nextPosition = Math.min(finish, positions.you + value); setDie(value); setPositions((current) => ({ ...current, you: nextPosition })); if (nextPosition >= finish) { setWinner('you'); onReact('win'); return } setTurn('owl') }, [finish, onReact, positions.you, turn, winner])
  useEffect(() => { if (turn !== 'owl' || winner) return undefined; const timer = window.setTimeout(() => { const value = Math.floor(Math.random() * (difficulty === 'easy' ? 4 : 6)) + 1; const nextPosition = Math.min(finish, positions.owl + value); setDie(value); setPositions((current) => ({ ...current, owl: nextPosition })); if (nextPosition >= finish) { setWinner('owl'); onReact('draw') } else setTurn('you') }, difficulty === 'hard' ? 480 : 720); return () => window.clearTimeout(timer) }, [difficulty, finish, onReact, positions.owl, turn, winner])
  const reset = () => { setPositions({ you: 0, owl: 0 }); setTurn('you'); setDie(null); setWinner(null) }; const progress = (value) => `${Math.round((value / finish) * 100)}%`
  return <div className="dk-game-panel dk-modern-game-panel dk-ludo-panel"><div className="dk-game-toolbar"><span className="dk-live-status"><i />{winner ? `${winner === 'you' ? 'You' : 'Owl'} reached the nest` : turn === 'you' ? 'Your turn to roll' : 'Owl is rolling'}</span><span className="dk-score-chip">{DIFFICULTIES[difficulty].label} race</span></div><div className="dk-ludo-track" aria-label="Ludo race track"><div className="dk-ludo-lane"><span className="dk-ludo-lane-label">You</span><div className="dk-ludo-progress"><i style={{ width: progress(positions.you) }} /><b style={{ left: progress(positions.you) }}>●</b></div><span className="dk-ludo-home">Nest</span></div><div className="dk-ludo-lane"><span className="dk-ludo-lane-label">Owl</span><div className="dk-ludo-progress owl"><i style={{ width: progress(positions.owl) }} /><b style={{ left: progress(positions.owl) }}>🦉</b></div><span className="dk-ludo-home">Nest</span></div></div><div className="dk-ludo-die" aria-live="polite">{die || '—'}</div><div className="dk-game-footer"><p>{winner ? 'The race is complete. Ready for another roll?' : `Roll the die and move ${DIFFICULTIES[difficulty].label === 'Easy' ? 'at a gentle pace' : 'towards the nest'}.`}</p><div className="dk-ludo-actions"><button type="button" className="dk-online-primary" onClick={roll} disabled={turn !== 'you' || Boolean(winner)}>Roll die</button><button type="button" className="dk-secondary-button" onClick={reset}>Restart</button></div></div></div>
}

export function GameComponent({ gameId, onReact, difficulty }) { if (gameId === 'memory') return <MemoryGame onReact={onReact} difficulty={difficulty} />; if (gameId === 'snake') return <SnakeGame onReact={onReact} difficulty={difficulty} />; if (gameId === 'connect') return <ConnectFourGame onReact={onReact} difficulty={difficulty} />; if (gameId === 'ludo') return <LudoGame onReact={onReact} difficulty={difficulty} />; if (gameId === 'chess') return <ChessGame onReact={onReact} difficulty={difficulty} />; return <TicTacToeGame onReact={onReact} difficulty={difficulty} /> }


const CHESS_SYMBOLS = { wp: '♙', wr: '♖', wn: '♘', wb: '♗', wq: '♕', wk: '♔', bp: '♟', br: '♜', bn: '♞', bb: '♝', bq: '♛', bk: '♚' }
const CHESS_BACK = ['br','bn','bb','bq','bk','bb','bn','br']; const CHESS_PAWNS = Array(8).fill('bp'); const CHESS_FRONT = ['wr','wn','wb','wq','wk','wb','wn','wr'];
function chessStart() { return [...CHESS_BACK, ...CHESS_PAWNS, ...Array(32).fill(null), ...CHESS_PAWNS.map(() => 'wp'), ...CHESS_FRONT] }
function chessMoves(board, from) { const piece = board[from]; if (!piece) return []; const color = piece[0]; const type = piece[1]; const row = Math.floor(from / 8); const col = from % 8; const moves = []; const add = (r, c, slide = false) => { if (r < 0 || r > 7 || c < 0 || c > 7) return false; const to = r * 8 + c; if (!board[to]) { moves.push(to); return slide } if (board[to][0] !== color) moves.push(to); return false }
  if (type === 'p') { const dir = color === 'w' ? -1 : 1; const start = color === 'w' ? 6 : 1; const next = (row + dir) * 8 + col; if (row + dir >= 0 && row + dir < 8 && !board[next]) { moves.push(next); if (row === start && !board[(row + dir * 2) * 8 + col]) moves.push((row + dir * 2) * 8 + col) } for (const dc of [-1, 1]) { const r = row + dir; const c = col + dc; if (r >= 0 && r < 8 && c >= 0 && c < 8) { const target = board[r * 8 + c]; if (target && target[0] !== color) moves.push(r * 8 + c) } } }
  if (type === 'n') [[-2,-1],[-2,1],[-1,-2],[-1,2],[1,-2],[1,2],[2,-1],[2,1]].forEach(([dr,dc]) => add(row + dr, col + dc))
  if (type === 'k') [[-1,-1],[-1,0],[-1,1],[0,-1],[0,1],[1,-1],[1,0],[1,1]].forEach(([dr,dc]) => add(row + dr, col + dc))
  if (['b','r','q'].includes(type)) { const dirs = type === 'b' ? [[-1,-1],[-1,1],[1,-1],[1,1]] : type === 'r' ? [[-1,0],[1,0],[0,-1],[0,1]] : [[-1,-1],[-1,1],[1,-1],[1,1],[-1,0],[1,0],[0,-1],[0,1]]; dirs.forEach(([dr,dc]) => { let r = row + dr; let c = col + dc; while (add(r, c, true)) { r += dr; c += dc } }) }
  return moves }
function chessLegalMoves(board, color) { return board.flatMap((piece, from) => piece?.[0] === color ? chessMoves(board, from).map(to => ({ from, to })) : []) }
export function ChessGame({ onReact, difficulty = 'standard' }) { const [board, setBoard] = useState(chessStart); const [selected, setSelected] = useState(null); const [turn, setTurn] = useState('w'); const [winner, setWinner] = useState(null); const move = (to) => { if (winner || turn !== 'w') return; const legal = selected !== null && chessMoves(board, selected).includes(to); if (!legal) { setSelected(board[to]?.[0] === 'w' ? to : null); return } const next = [...board]; const moving = next[selected]; next[to] = moving[1] === 'p' && Math.floor(to / 8) === 0 ? 'wq' : moving; next[selected] = null; if (next[to] === 'bk') { setWinner('you'); onReact('win') } else { setTurn('b'); setSelected(null) } setBoard(next) }
  useEffect(() => { if (turn !== 'b' || winner) return undefined; const timer = window.setTimeout(() => { const moves = chessLegalMoves(board, 'b'); if (!moves.length) { setWinner('you'); onReact('win'); return } const captures = moves.filter(({ to }) => board[to]?.[0] === 'w'); const pool = difficulty === 'hard' && captures.length ? captures : moves; const choice = pool[Math.floor(Math.random() * pool.length)]; const next = [...board]; const moving = next[choice.from]; next[choice.to] = moving[1] === 'p' && Math.floor(choice.to / 8) === 7 ? 'bq' : moving; next[choice.from] = null; if (next[choice.to] === 'wk') { setWinner('owl'); onReact('draw') } setBoard(next); setTurn('w') }, difficulty === 'hard' ? 320 : difficulty === 'easy' ? 800 : 560); return () => window.clearTimeout(timer) }, [board, difficulty, onReact, turn, winner])
  const reset = () => { setBoard(chessStart()); setSelected(null); setTurn('w'); setWinner(null) }; const legalTargets = selected === null ? [] : chessMoves(board, selected)
  return <div className="dk-game-panel dk-modern-game-panel dk-chess-panel"><div className="dk-game-toolbar"><span className="dk-live-status"><i />{winner ? `${winner === 'you' ? 'You' : 'Owl'} win` : turn === 'w' ? 'Your turn' : 'Owl is thinking'}</span><span className="dk-score-chip">{DIFFICULTIES[difficulty].label} chess</span></div><div className="dk-chess-board" role="grid" aria-label="Owl Chess board">{board.map((piece, index) => <button type="button" key={index} className={`dk-chess-square ${(Math.floor(index / 8) + index) % 2 ? 'is-dark' : 'is-light'} ${selected === index ? 'is-selected' : ''} ${legalTargets.includes(index) ? 'is-target' : ''}`} onClick={() => move(index)} aria-label={`${String.fromCharCode(97 + index % 8)}${8 - Math.floor(index / 8)}${piece ? ` ${piece}` : ''}`}>{piece ? CHESS_SYMBOLS[piece] : legalTargets.includes(index) ? '·' : ''}</button>)}</div><div className="dk-game-footer"><p aria-live="polite">{winner ? 'A thoughtful round. Ready to reset the board?' : 'Tap a white piece, then tap a highlighted square.'}</p><button type="button" className="dk-secondary-button" onClick={reset}>Restart</button></div></div> }

