import { Link } from 'react-router-dom'

export default function AuthShell({ eyebrow, title, subtitle, children, footer, alternateLabel, alternateLink, alternateText }) {
  return (
    <div className="auth-page min-h-screen" style={{ background: 'var(--auth-page)', color: 'var(--auth-ink)' }}>
      <header className="flex items-center justify-between px-4 py-4 sm:px-10 sm:py-5">
        <Link to="/" className="flex items-center gap-3" aria-label="Go to DataKwest home"><img src="/datakwest_logo_lockup.png" alt="DataKwest logo" className="h-12 w-48 object-contain object-left" /><div><p className="text-sm font-black tracking-tight" style={{ color: 'var(--auth-ink)' }}>DATAKWEST</p><p className="text-[10px] font-semibold uppercase tracking-[0.18em]" style={{ color: 'var(--auth-muted)' }}>Digital skills, one mission at a time</p></div></Link>
        <Link to="/" className="hidden text-sm font-bold sm:block" style={{ color: 'var(--auth-link)' }}>Explore Datakwest</Link>
      </header>
      <main className="mx-auto grid max-w-6xl gap-6 px-4 pb-10 pt-2 sm:gap-8 sm:px-6 sm:pb-12 sm:pt-4 lg:grid-cols-[0.8fr_1.2fr] lg:items-center lg:px-10 lg:pt-10">
        <section className="hidden rounded-[2rem] p-10 lg:block" style={{ background: '#0A2342', boxShadow: '0 20px 70px rgba(10,35,66,0.16)' }}><p className="text-xs font-bold uppercase tracking-[0.22em]" style={{ color: '#D4AF37' }}>Your digital skills journey</p><h1 className="mt-5 text-4xl font-bold leading-tight text-white">Learn what moves your life forward.</h1><p className="mt-5 text-sm leading-7" style={{ color: 'rgba(255,255,255,0.7)' }}>Datakwest gives you a practical path across the digital skills that matter—from first principles to portfolio-ready proof.</p><div className="mt-10 space-y-4"><div className="flex items-center gap-3"><span className="h-8 w-8 rounded-lg flex items-center justify-center text-xs font-black" style={{ background: 'rgba(212,175,55,0.16)', color: '#D4AF37' }}>01</span><span className="text-sm font-bold text-white">Short lessons that build momentum</span></div><div className="flex items-center gap-3"><span className="h-8 w-8 rounded-lg flex items-center justify-center text-xs font-black" style={{ background: 'rgba(255,255,255,0.1)', color: 'white' }}>02</span><span className="text-sm font-bold text-white">Projects that make skills visible</span></div><div className="flex items-center gap-3"><span className="h-8 w-8 rounded-lg flex items-center justify-center text-xs font-black" style={{ background: 'rgba(255,255,255,0.1)', color: 'white' }}>03</span><span className="text-sm font-bold text-white">AI guidance when you get stuck</span></div></div></section>
        <section className="auth-card mx-auto w-full max-w-xl rounded-[2rem] p-6 sm:p-10" style={{ background: 'var(--auth-surface)', boxShadow: '0 20px 70px rgba(10,35,66,0.1)' }}><div className="mb-8"><p className="text-xs font-bold uppercase tracking-[0.2em]" style={{ color: 'var(--auth-eyebrow)' }}>{eyebrow}</p><h2 className="mt-3 text-3xl font-bold tracking-tight" style={{ color: 'var(--auth-ink)' }}>{title}</h2><p className="mt-3 text-sm leading-6" style={{ color: 'var(--auth-muted)' }}>{subtitle}</p></div>{children}{footer && <p className="mt-7 text-center text-sm" style={{ color: 'var(--auth-muted)' }}>{footer}</p>}{alternateLabel && <p className="mt-3 text-center text-sm" style={{ color: 'var(--auth-muted)' }}>{alternateLabel} <Link to={alternateLink} className="font-bold" style={{ color: 'var(--auth-ink)' }}>{alternateText}</Link></p>}</section>
      </main>
    </div>
  )
}
