import { Link } from 'react-router-dom'

export default function AuthShell({ eyebrow, title, subtitle, children, footer, alternateLabel, alternateLink, alternateText }) {
  return (
    <div className="min-h-screen" style={{ background: '#F4F7FB' }}>
      <header className="flex items-center justify-between px-6 py-5 sm:px-10">
        <Link to="/" className="flex items-center gap-3" aria-label="Go to DataKwest home"><div className="h-10 w-10 rounded-xl flex items-center justify-center font-black" style={{ background: '#0A2342', color: '#D4AF37' }}>D</div><div><p className="text-sm font-black tracking-tight" style={{ color: '#0A2342' }}>DATAKWEST</p><p className="text-[10px] font-semibold uppercase tracking-[0.18em]" style={{ color: '#8391A7' }}>Digital skills, one mission at a time</p></div></Link>
        <Link to="/" className="hidden text-sm font-bold sm:block" style={{ color: '#2456A6' }}>Explore Datakwest</Link>
      </header>
      <main className="mx-auto grid max-w-6xl gap-8 px-6 pb-12 pt-4 lg:grid-cols-[0.8fr_1.2fr] lg:items-center lg:px-10 lg:pt-10">
        <section className="hidden rounded-[2rem] p-10 lg:block" style={{ background: '#0A2342', boxShadow: '0 20px 70px rgba(10,35,66,0.16)' }}><p className="text-xs font-bold uppercase tracking-[0.22em]" style={{ color: '#D4AF37' }}>Your digital skills journey</p><h1 className="mt-5 text-4xl font-bold leading-tight text-white">Learn what moves your life forward.</h1><p className="mt-5 text-sm leading-7" style={{ color: 'rgba(255,255,255,0.7)' }}>Datakwest gives you a practical path across the digital skills that matter—from first principles to portfolio-ready proof.</p><div className="mt-10 space-y-4"><div className="flex items-center gap-3"><span className="h-8 w-8 rounded-lg flex items-center justify-center text-xs font-black" style={{ background: 'rgba(212,175,55,0.16)', color: '#D4AF37' }}>01</span><span className="text-sm font-bold text-white">Short lessons that build momentum</span></div><div className="flex items-center gap-3"><span className="h-8 w-8 rounded-lg flex items-center justify-center text-xs font-black" style={{ background: 'rgba(255,255,255,0.1)', color: 'white' }}>02</span><span className="text-sm font-bold text-white">Projects that make skills visible</span></div><div className="flex items-center gap-3"><span className="h-8 w-8 rounded-lg flex items-center justify-center text-xs font-black" style={{ background: 'rgba(255,255,255,0.1)', color: 'white' }}>03</span><span className="text-sm font-bold text-white">AI guidance when you get stuck</span></div></div></section>
        <section className="mx-auto w-full max-w-xl rounded-[2rem] bg-white p-7 sm:p-10" style={{ boxShadow: '0 20px 70px rgba(10,35,66,0.1)' }}><div className="mb-8"><p className="text-xs font-bold uppercase tracking-[0.2em]" style={{ color: '#9A7610' }}>{eyebrow}</p><h2 className="mt-3 text-3xl font-bold tracking-tight" style={{ color: '#0A2342' }}>{title}</h2><p className="mt-3 text-sm leading-6" style={{ color: '#6B7A99' }}>{subtitle}</p></div>{children}{footer && <p className="mt-7 text-center text-sm" style={{ color: '#6B7A99' }}>{footer}</p>}{alternateLabel && <p className="mt-3 text-center text-sm" style={{ color: '#6B7A99' }}>{alternateLabel} <Link to={alternateLink} className="font-bold" style={{ color: '#0A2342' }}>{alternateText}</Link></p>}</section>
      </main>
    </div>
  )
}
